# Description:
  # This playbook will apply a list of loaded PTFs
  # 
  # Reference: https://github.com/IBM/ansible-for-i/tree/devel/roles/apply_ptf

# Parameters:
  # to_be_applied_list    -- list -- List of loaded PTFs to be applied. ptf_id and product are required.
  # apply_all_loaded_ptfs -- bool -- Controls whether all loaded PTFs will be applied. When its value is true,
  #                                  'to_be_applied_list' will be ignored. The default value is False.
  # temp_or_perm          -- str  -- Controls whether the target PTFs will be permanent applied or temporary applied.
  #                                  Value can be '*TEMP' or '*PERM'. Default value is '*TEMP'.
  # delayed_option        -- str  -- Controls whether the PTF is delayed apply or not. Value can be '*YES', '*NO'
  #                                  or '*IMMDLY'. Default value is '*IMMDLY'.
  # auto_ipl              -- bool -- Controls whether an immediate reboot will be launched automatically if
  #                                  at least one ptf requests an IPL for permanent applied or temporary applied.
  #                                  The default value is false.
  
# Sample:
  # to_be_loaded_list:
  #   - {'ptf_id':'SI73543', 'product':'5770UME'}
  #   - {'ptf_id':'SI73430', 'product':'5733SC1'}
  # apply_all_loaded_ptfs: False
  # temp_or_perm: "*TEMP"
  # delayed_option: "*IMMDLY"
  # auto_ipl: False

---
- name: Apply a list of loaded PTFs 
  hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi
  
  vars:
    to_be_applied_list: "{{ to_be_applied_list | default([]) }}"
    apply_all_loaded_ptfs: "{{ apply_all_loaded_ptfs | default(False) }}"
    temp_or_perm: "{{ temp_or_perm | default(*TEMP) }}"
    delayed_option: "{{ delayed_option | default(*IMMDLY) }}"
    auto_ipl: "{{ auto_ipl | default(False) }}"

  tasks:
    - name: Apply a list of loaded PTFs
      include_role:
        name: apply_ptf
      register: results
      ignore_errors: yes

    - name: results
      debug:
        msg: "{{ results }}"
        