# Description:
  # This playbook will check PTFs status according to given PTF list, and returned
  # all the PTFs info, status, not loaded PTF list and already loaded PTF list
  #
  # Reference: https://github.com/IBM/ansible-for-i/tree/devel/roles/check_ptf

# Parameters:
  # check_ptf_list -- list -- PTF list will be checked. ptf_id is required. product and release are required
  #                           if check_product is true and PTF does not exist.

# Sample:
  # check_ptf_list:
  #   - {'ptf_id':'SI70544', 'product':'5770SS1', 'release': 'V7R4M0'}
  #   - {'ptf_id':'SI70931', 'product':'5770SS1', 'release': 'V7R4M0'}
  #   - {'ptf_id':'SI72305', 'product':'5770SS1', 'release': 'V7R4M0'}
  #   - {'ptf_id':'SI71691', 'product':'5770SS1', 'release': 'V7R4M0'}

---
- name: IBM i check a set of PTFs
  hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi

  vars:
    check_ptf_list: "{{ check_ptf_list }}"

  tasks:
    - name: Check PTFs status
      include_role:
        name: check_ptf
