
# Description:
  # This playbook will all list interim fixes (ifix) on the system
  # 
  # Reference: https://ibm.github.io/ansible-power-aix/modules/emgr.html

# Parameters:
  
# Sample:

---
- name: List all interim fixes (ifix) on the system
  hosts: all
  gather_facts: false
  collections:
   - ibm.power_aix
  
  vars: 

  tasks:
    - name: List all interim fixes (ifix) on the system
      emgr:
        action: list
      become: yes
      register: results

    - name: results
      debug:
        msg: "{{ results }}"