---
- name: Gather all lvm facts
  hosts: all
  gather_facts: no
  collections:
   - ibm.power_aix

  tasks:

  - name: Gather all lvm facts
    lvm_facts:

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts.LVM