---
- name: Gather all lvm facts
  hosts: all
  gather_facts: no
  collections:
   - ibm.power_aix

  tasks:

  - name: Gather all lvm facts
    lvm_facts:

  - name: List all VGs
    ansible.builtin.debug:
      var: ansible_facts.LVM.VGs

  - name: List all PVs
    ansible.builtin.debug:
      var: ansible_facts.LVM.PVs