---
- name: AIX Patching
  hosts: all
  gather_facts: no
  collections:
   - ibm.power_aix

  vars: 
    action_str: "{{ action_str | default(list_fixes) }}"
    device: "{{ device | default(/usr/sys/inst.images) }}"
    install_list: "{{ install_list | default(all) }}"
    # action_str: "list_fixes"
    # device: "/usr/sys/inst.images"
    # install_list: "all"

  tasks:
  - name: Patching
    become: yes
    ibm.power_aix.installp:
      action: "{{ action_str }}"
      device: "{{ device }}"
      install_list: "{{ install_list }}"
      dependencies: yes
      agree_licenses: yes
    register: result

  - fail:
      msg: "{{ result.stderr }}"
    when: result.stderr != ""

  - debug:
      var: result.stdout