---
- name: Gather all lvm facts
  hosts: all
  gather_facts: no
  collections:
   - ibm.power_aix

  tasks:

  - name: Gather all lvm facts
    lvm_facts:

  - name: Set rootvg var
    set_fact:
      rootvg: "{{ ansible_facts.LVM.LVs.hd5.vg }}"

  - name: Set rootvg_facts var
    set_fact:
      rootvg_facts: "{{ ansible_facts.LVM.VGs[rootvg] }}"

  - name: Set pvs var
    set_fact:
      pvs: "{{ ansible_facts.LVM.PVs }}"

  - name: Set pvs_by_vg var
    set_fact: { "pv_{{ item.value.vg }}": "{{ item.key }}" }
    loop: "{{ ansible_facts.LVM.PVs | dict2items }}"

  - name: print rootvg hdisk
    ansible.builtin.debug: 
      var: pv_rootvg

#   - name: Set hdisk var
#     set_fact:
#       rootvg_facts: "{{ ansible_facts.LVM.VGs[rootvg] }}"

# community.general.json_query('domain.server[?cluster==`cluster1`].port') | join(', ') }}"

#   - name: Show {{ hdisk }} PV
#     ansible.builtin.debug:
#       var: ansible_facts.LVM.PVs[hdisk]