---
- name: Gather all lvm facts
  hosts: all
  gather_facts: no
  collections:
   - ibm.power_aix

  tasks:

  - name: Gather all lvm facts
    lvm_facts:

  - name: Set rootvg var
    ansible.builtin.set_fact:
      rootvg: "{{ ansible_facts.LVM.LVs.hd5.vg }}"

  - name: Set hdisk var
    ansible.builtin.set_fact:
      hdisk: "{{ ansible_facts.LVM.VGs[rootvg] }}"

  - name: Show {{ hdisk }} PV
    ansible.builtin.debug:
      var: ansible_facts.LVM.PVs[hdisk]