---
- name: Run CL Commmand
  hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi
  
  vars:
    command: "{{ command }}"

  tasks:
  - name: Run CL Command 
    ibmi_cl_command:
      cmd: "{{ command }}"
      joblog: true
    register: result

  - name: Display errors
    debug:
      msg: "{{ result.stderr_lines }}"
    when: result.stderr != ""

  - name: Display output
    debug:
      msg: "{{ result.stdout_lines }}"
    when: result.stdout != ""